"""Abstract agent adapter interface: normalization, fresh-turn detection, and model application."""
from __future__ import annotations
from typing import Protocol
class AgentAdapter(Protocol):
    name: str
    def detect(self) -> bool: ...
    def capabilities(self): ...
    def normalize_request(self, raw: dict): ...
    def apply_model(self, raw: dict, model: str) -> dict: ...
    def is_new_turn(self, raw: dict) -> bool: ...
    def conversation_key(self, raw: dict) -> str: ...
