"""Abstract provider interface: endpoints, authentication, and request/response translation."""
from __future__ import annotations
from typing import Protocol
class Provider(Protocol):
    name: str
    def translate(self, request: dict, model: str) -> dict: ...
    def parse_response(self, raw: dict) -> dict: ...
    def endpoint(self) -> str: ...
